apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    type: front-endReplica
spec:
  replicas: 3
  template:
    metadata:
      labels:
        type: front-end
    spec:
      containers:
        - name: mypod
          image: nginx