apiVersion: apps/vl
kind: ReplicaSet
metadata:
  labels:
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      labels:
        type: front-end
    spec:
      containers:
        - name: mypod
          image: nginx