apiVersion: v1
kind: Service
metadata:
  name: sensei
  labels:
    app: sensei
spec:
  ports:
    - port: 8080
  selector:
    app: sensei
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: sensei
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sensei
  labels:
    app: sensei
spec:
  selector:
    matchLabels:
      app: sensei
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sensei
        tier: frontend
    spec:
      containers:
      - image: ceciliaosorio/sensei:v2
        name: sensei
        env:
        - name: sensei_DB_HOST
          value: sensei-mysql
        - name: sensei_DB_PASSWORD
          value: password
          # valueFrom:
          #   secretKeyRef:
          #     name: mysql-pass
          #     key: password
        ports:
        - containerPort: 3000
          name: sensei
        volumeMounts:
        - name: sensei-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: sensei-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
