apiVersion: v1
kind: Service
metadata:
  name: sensei-mysql
  labels:
    app: sensei
spec:
  ports:
    - port: 3306
  selector:
    app: sensei
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: sensei
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sensei-mysql
  labels:
    app: sensei
spec:
  selector:
    matchLabels:
      app: sensei
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sensei
        tier: mysql
    spec:
      containers:
      - image: tcolas673/sensei-mysql:v0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
          # valueFrom:
          #   secretKeyRef:
          #     name: mysql-pass
          #     key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
