apiVersion: apps/vl
kind: Deployment
metadata:
  labels:
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      labels:
        type: front-end
    spec:
      containers:
        - name: mypod
          image: nginx

# only difference between replicaSet was that the kind is Deployment
# can use Deployment for rolling updates and rolling them back