apiVersion: v1
kind: Service
metadata:
  name: myapp-services
spec:
  type: NodePort
  ports:
    - targetPorts: 80
      port: 80
      nodePort: 30008
  selector:
    # label info from desired pod/s